name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Deploy
        run: |
          # Enable error propagation
          set -e

          # Setting up the SSH configuration
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          echo "$SSH_FINGERPRINT" > ~/.ssh/known_hosts
          chmod 700 -R ~/.ssh

          # Transfer files
          EXCLUDED_ARGS=()
          for excludedFile in $EXCLUDED_FILES; do
            EXCLUDED_ARGS+=("--exclude=${excludedFile}")
          done
          rsync --exclude=.git --exclude-from=.gitignore ${EXCLUDED_ARGS[*]} \
            --delete -cpqr . "$SERVER_SSH":"$SERVER_PATH"
        env:
          SERVER_SSH: user@slack.mod-harbour.org
          SERVER_PATH: slack-logs
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_FINGERPRINT: slack.mod-harbour.org ${{ secrets.SERVER_SSH_FINGERPRINT }}
          EXCLUDED_FILES: .gitignore .github LICENSE README.md README.es.md
